---
title: Lost River Ridge Labradors
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  home_sections:
    title: Sections
    output: true
  uploads:
    title: Uploads
    output: true
email: lostriverridgelabradors@gmail.com
description: Lost River Ridge Labradors is a breeder of Chocolate Lab Puppies in Central
  Indiana
baseurl: 
url: https://lostriverridgelabradors.com
theme: minima
plugins:
- jekyll-feed
